[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["@netlify/functions"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/groq"
  to = "/.netlify/functions/groq"
  status = 200

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/api/adsense"
  to = "/.netlify/functions/adsense"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    cache-control = "public,max-age=31536000,immutable"